# ── Stage 1: Builder ─────────────────────────────────────────────────────────
FROM node:20-alpine AS builder

RUN apk add --no-cache openssl libc6-compat
WORKDIR /app

# Install deps first — cached unless package-lock.json changes
# .npmrc carries legacy-peer-deps=true (next-auth beta peer conflict with nodemailer 8)
COPY package.json package-lock.json .npmrc ./
COPY prisma ./prisma/
RUN npm ci

# Dummy build-time vars — prisma generate needs a DSN format but no live DB.
# Real values are injected by Cloud Run at runtime; these never run in production.
ENV DATABASE_URL="postgresql://build:build@localhost:5432/build"
ENV AUTH_SECRET="build-placeholder-32-chars-minimum!"
ENV ENCRYPTION_KEY="0000000000000000000000000000000000000000000000000000000000000000"
ENV NEXTAUTH_URL="https://lstudy.in"

RUN npx prisma generate

COPY . .
RUN npm run build

# ── Stage 2: Runner ───────────────────────────────────────────────────────────
# next.config.ts has output:"standalone" — only copy the self-contained bundle.
FROM node:20-alpine AS runner

RUN apk add --no-cache openssl libc6-compat
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=8080
ENV HOSTNAME=0.0.0.0

COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static     ./.next/static
COPY --from=builder /app/public           ./public

EXPOSE 8080

# Migrations run in CI (prisma migrate deploy) before this image starts.
# server.js is generated by Next.js standalone mode and reads PORT automatically.
CMD ["node", "server.js"]
