- name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}      # Ye exact naam hona chahiye
          username: ${{ secrets.SSH_USER }}  # Ye exact naam hona chahiye
          key: ${{ secrets.SSH_KEY }}        # Ye exact naam hona chahiye
          port: 22
          script: |
            cd /var/www/cyber_library
            git pull origin main
            npm install
            npx prisma generate
            NODE_OPTIONS="--max-old-space-size=1024" npm run build
            pm2 restart cyber-app