- name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /var/www/cyber_library
            git pull origin main
            npm install
            npm run build
            pm2 restart all || pm2 start npm --name "cyber-lib" -- start